import { lazy, Suspense, useEffect, useState } from 'react'
import { motion, useReducedMotion, useScroll, useSpring } from 'framer-motion'
const ThreeScene = lazy(() => import('./ThreeScene'))

const projects=[
 {n:'01',title:'NoShowCalc',type:'Healthcare Operations',desc:'A focused calculator that makes the annual cost of missed appointments visible.',metric:'$78K',metricLabel:'illustrative annual opportunity',live:'https://nikhilr23.github.io/noshowcalc/',code:'https://github.com/Nikhilr23/noshowcalc',tone:'lime'},
 {n:'02',title:'ProfitQuote',type:'Pricing Intelligence',desc:'A local-first quoting tool that exposes true cost, profit, and target margin before a quote is sent.',metric:'35%',metricLabel:'target margin model',live:'https://nikhilr23.github.io/profitquote/',code:'https://github.com/Nikhilr23/profitquote',tone:'cream'},
 {n:'03',title:'ConvertLab',type:'Privacy-first Utility',desc:'Browser-based file conversion designed around clear limits and files that stay on the device.',metric:'0',metricLabel:'uploads required',live:'https://nikhilr23.github.io/convertlab/',code:'https://github.com/Nikhilr23/convertlab',tone:'blue'}
]
const skills=[['Epic / EHR','Clinical workflows, access, operations and end-user support.'],['Identity & Access','RBAC, access reviews, onboarding and audit readiness.'],['Data & Interoperability','SQL, Power BI, HL7 and FHIR for clearer system decisions.'],['Product Building','Focused browser tools that solve narrow, visible problems.']]
const roles=[['2025 — NOW','Clinical Systems Analyst','Cleveland Clinic'],['2025','Epic Associate Application Analyst','Prime Healthcare'],['2023 — 2025','M.S. Health Informatics','University of Findlay']]

const Reveal=({children,className='',delay=0}:{children:React.ReactNode,className?:string,delay?:number})=>{const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:50}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.18}} transition={{duration:.85,delay,ease:[.16,1,.3,1]}}>{children}</motion.div>}

export default function App(){
 const [menu,setMenu]=useState(false), reduce=useReducedMotion(); const {scrollYProgress}=useScroll(); const progress=useSpring(scrollYProgress,{stiffness:120,damping:28,mass:.3})
 useEffect(()=>{document.body.style.overflow=menu?'hidden':'';return()=>{document.body.style.overflow=''}},[menu])
 return <div className="site-shell">
  <motion.div className="progress" style={{scaleX:progress}}/><div className="grain" aria-hidden="true"/>
  <header className="topbar"><a className="logo" href="#top"><b>NR</b><span>NIKHIL REDDY</span></a><nav><a href="#work">Work</a><a href="#expertise">Expertise</a><a href="#about">About</a></nav><a className="status" href="#contact"><i/>Available for opportunities</a><button className={`menu ${menu?'open':''}`} onClick={()=>setMenu(!menu)} aria-label="Toggle menu"><i/><i/></button></header>
  <aside className={`drawer ${menu?'open':''}`}><nav>{['Work','Expertise','About','Contact'].map((x,i)=><a key={x} style={{transitionDelay:`${150+i*70}ms`}} href={`#${x.toLowerCase()}`} onClick={()=>setMenu(false)}>{x}<span>0{i+1}</span></a>)}</nav><div><a href="https://github.com/Nikhilr23" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/in/nikhil-reddy-chitkula/" target="_blank">LinkedIn ↗</a></div></aside>
  <main>
   <section className="hero" id="top"><div className="hero-grid"><motion.div className="hero-copy" initial={reduce?false:{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{duration:1,delay:.25,ease:[.16,1,.3,1]}}><p className="eyebrow">HEALTHCARE SYSTEMS × DIGITAL PRODUCTS</p><h1><span>MAKING COMPLEX</span><em>SYSTEMS HUMAN.</em></h1><p className="intro">I connect healthcare workflows, secure access, data, and practical software—turning operational friction into tools people can actually use.</p><div className="hero-links"><a className="primary" href="#work">Explore work <span>↘</span></a><a href="https://www.linkedin.com/in/nikhil-reddy-chitkula/" target="_blank">LinkedIn ↗</a></div></motion.div><div className="scene" aria-label="Interactive connected healthcare systems sculpture"><Suspense fallback={null}><ThreeScene/></Suspense></div><motion.div className="portrait" initial={reduce?false:{opacity:0,y:45,scale:1.03}} animate={{opacity:1,y:0,scale:1}} transition={{duration:1.2,delay:.4,ease:[.16,1,.3,1]}}><img src="assets/nikhil-portrait-cutout.webp" alt="Nikhil Reddy Chitkula"/></motion.div></div><div className="hero-bottom"><span>SCROLL TO EXPLORE</span><span>EPIC · IAM · HL7/FHIR · SQL</span></div></section>
   <div className="ticker"><div>NIKHIL REDDY <i>✦</i> HEALTHCARE IT <i>✦</i> PRODUCT BUILDER <i>✦</i> NIKHIL REDDY <i>✦</i> HEALTHCARE IT <i>✦</i> PRODUCT BUILDER <i>✦</i></div></div>
   <section className="work section" id="work"><Reveal className="section-title"><p>01 / SELECTED WORK</p><h2>Focused products.<br/><em>Clear outcomes.</em></h2></Reveal><div className="project-list">{projects.map((p,i)=><Reveal key={p.title} delay={i*.08}><article className={`project-card ${p.tone}`}><div className="project-copy"><p>{p.n} / {p.type}</p><h3>{p.title}</h3><span>{p.desc}</span><div><a href={p.live} target="_blank">Live product ↗</a><a href={p.code} target="_blank">Source ↗</a></div></div><div className="project-art"><span>{p.metricLabel}</span><strong>{p.metric}</strong><div className="orbit-art"><i/><i/><i/></div></div></article></Reveal>)}</div></section>
   <section className="expertise section" id="expertise"><Reveal className="section-title"><p>02 / CAPABILITIES</p><h2>Different disciplines.<br/><em>One system view.</em></h2></Reveal><div className="skill-grid">{skills.map((s,i)=><Reveal key={s[0]} delay={i*.07}><article><span>0{i+1}</span><div className="skill-icon"><i/><i/></div><h3>{s[0]}</h3><p>{s[1]}</p></article></Reveal>)}</div></section>
   <section className="about section" id="about"><div className="about-visual"><Reveal><img src="assets/nikhil-portrait.jpg" alt="Nikhil Reddy"/><span>NRC / SYSTEMS ANALYST</span></Reveal></div><Reveal className="about-copy"><p>03 / ABOUT</p><h2>Between the workflow and the system.</h2><p>My work sits at the intersection of healthcare operations, application support, identity, data, and product thinking. I start with what people need to accomplish, then make the technology clearer.</p><blockquote>Understand the workflow before changing the tool.</blockquote></Reveal></section>
   <section className="experience section"><Reveal className="section-title"><p>04 / EXPERIENCE</p><h2>Healthcare context.<br/><em>Builder mindset.</em></h2></Reveal><div className="timeline">{roles.map((r,i)=><Reveal key={r[0]} delay={i*.06}><article><span>{r[0]}</span><h3>{r[1]}</h3><p>{r[2]}</p><i>↗</i></article></Reveal>)}</div></section>
   <section className="contact section" id="contact"><Reveal><p>05 / LET'S CONNECT</p><a className="contact-title" href="https://www.linkedin.com/in/nikhil-reddy-chitkula/" target="_blank">BUILD SOMETHING<br/><em>USEFUL TOGETHER.</em><span>↗</span></a><div className="contact-foot"><span>OPEN TO HEALTHCARE IT & PRODUCT-MINDED ROLES</span><div><a href="https://github.com/Nikhilr23" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/in/nikhil-reddy-chitkula/" target="_blank">LinkedIn ↗</a></div></div></Reveal></section>
  </main><footer><span>© 2026 NIKHIL REDDY CHITKULA</span><a href="#top">BACK TO TOP ↑</a></footer>
 </div>
}
